### ISSUE TITLE
svg for expo logo

### ISSUE THREAD

**Issue by rabaut** [dawnlabs/next-site#10]
We need an svg for the Expo logo. Should we just scrap it from their site?

**Comment by jakedex** [comment]
If you can find one, yeah! Otherwise, I think the PNG in the figma doc is pretty high-res... 

![expo](https://user-images.githubusercontent.com/10369094/52013950-f4646480-24a3-11e9-9eee-bfecf56b0725.png)

**Comment by rabaut** [comment]
Okay that's a very nice png, I only recommend svg over that because it seems to be what they do: 

https://github.com/dawnlabs/next-site/tree/master/components/icons/companies

**Comment by jakedex** [comment]
Word. Yeah, if you can find an SVG that'd be preferred!

**Comment by jakedex** [comment]
Not sure how it'll turn out, but could maybe use something like this as well: https://vectormagic.com/

**Comment by rabaut** [comment]
Okay I just used the one from their site, it was nicer than what came out of vectormagic.
