### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/next-site#2]
the navbar should behave the same as it does on the homepage: i.e. part of the dotted background when it's in the hero, then "breaks out" as you scroll

https://cl.ly/54ecabc785ee

**Comment by mfix22** [comment]
@jakedex i don't know if we want that 😬  As of now that is specific to the homepage. Plus it's pretty jank on the homepage as it is.

**Comment by jakedex** [comment]
I think that's because the homepage is currently the only page with the dotted BG. As for janky-ness, I think we're fine leaving that to them to fix.

**Comment by mfix22** [comment]
Right, but we would be adding that same jankiness to our page if we added it?

**Comment by briandennis** [comment]
I think we should use the same behavior as the home page if at all possible.

@mfix22 what jank are you talking about?
