### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/next-site#30]
## "Lightning Fast Navigation" Section
- [x] Should be a space in: "application is.Eliminating"
- [x] Button should link to correct location

## "Native Features" Section
- [x] These bullets need to be aligned
- [x] First row should have larger margin-bottom (24px according to mock):
<img width="848" alt="Screenshot 2019-03-13 13 48 35" src="https://user-images.githubusercontent.com/8397708/54313543-d572eb00-4596-11e9-8cff-0b58d0641e16.png">

**Comment by mfix22** [comment]
I don't know if this is just me, but the graphics do not look centered w.r.t the rest:
<img width="1280" alt="Screenshot 2019-03-13 13 46 55" src="https://user-images.githubusercontent.com/8397708/54313434-93e24000-4596-11e9-9314-3b939bb67112.png">

**Comment by jakedex** [comment]
https://cl.ly/fb7f5d019b28

- [x] font-size should be the same as the other pages
- [x] spacing top/bottom should be the same as other pages (40px)
- [x] let's cut all the spacing here in half (on mobile) ~ https://cl.ly/e47263f93e0c

- [x] Does the `border-radius` for some of the elements in the mock website look wonky for you all as well? Maybe we just use static images for that part of the SVG?

**Comment by jakedex** [comment]
# Offline Support
- [x] `padding-top` should be 64px, not 48px
- [x] paragraph `max-width` should be 44rem
- [x] (mobile) let's make sure the wireless icon is vertically centered here ~ https://cl.ly/e88123a65581

**Comment by mfix22** [comment]
@jakedex what do you think about adding an online/offline listener to the page and doing something to the styling when the user goes offline? Not going as far as to make the site a PWA itself, but 🤷‍♂️
