### ISSUE TITLE
Add PWA to "Features" in the footer

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/next-site#31]

**Comment by rabaut** [comment]
Should this be a separate PR or included in the `features/pwa` branch?

**Comment by mfix22** [comment]
@jakedex are we sure we want to add this to the footer? If so, do you think it would be called "Mobile Sites" or PWAs?

**Comment by mfix22** [comment]
@raboid let's add it to the footer, calling the link `PWA`

**Comment by rabaut** [comment]
Closed by 16c40a47c9cc8dd1bc86db0386ee4956d4e6ece0
