### ISSUE TITLE
Change PWA customers header

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/next-site#32]
Should not say PWA. I was thinking something like:

> Who's Using Next.js for Mobile

**Comment by rabaut** [comment]
Closed by 822f0a2e9bc6cee6ee162a458a5a9e4ffd1fe3eb ?

**Comment by mfix22** [comment]
Want to make sure @jakedex is okay with the new header b4 closing

**Comment by jakedex** [comment]
👍
