### ISSUE TITLE
Hulu Case Study

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/next-site#33]
- [x] Optimize images (let's wait until everything is finalized first)
- [x] Spacing here is too big on large displays (https://cl.ly/1859b7a8aa72)
- [x] Use same button:hover effects as Integral case study (https://cl.ly/9322d50dc989)
- [x] Images should be exported as jpg (hulu grass logo and headshot of zack should be higher resolution)
- [x] Space between this paragraph and image should be doubled (on widths >=1200px) [https://cl.ly/8dcfc52a38fc]
- [x] subheading / heading / paragraph spacing (for all sections) should match mock (https://cl.ly/16556c78a7df)
- [x] Let's remove this? (https://cl.ly/2770e9ae0728)
- [x] Closing CTA (spacing, HR width, etc) should match Integral case study (https://cl.ly/b4a5e86a7d74) (don't forget mobile https://cl.ly/dad333e2a9a8 🙂)
- [x] On tablet-sized widths, the "Conclusion" link is getting awfully close to the image split. Let's decrease the split angle here as well? (https://cl.ly/ee01f7d6e26f)

**Comment by mfix22** [comment]
Adding to TODO list so feedback doesn't get lost:
- [x] "We’re going to take a photo of the team to replace the one of the people working."
- [x] Ensure show photos are approved before shipping

**Comment by jakedex** [comment]
Some more feedback after reviewing the latest: 

- [x] hero image should span full-width (like it does in mocks). i'm fine with the image width maxing out ~1600px.
    - i can get you a higher-res version if needed
    - we should also fix this corner (https://cl.ly/07b547366fc7)
    - hulu grass logo image width should be adjusted to match hero image width
- [x] this section (https://cl.ly/b40b26254af8) shouldn't be center-aligned (see mocks)
- [x] the following corners are missing transition gradients (https://cl.ly/4157e8aca15d and https://cl.ly/fe667210a23d)
- [x] if possible, let's update the image of zack to a higher resolution. (will probably require digging up the original image he sent over)
- [x] both corner and text glitching should be fixed (https://cl.ly/7c13497ad05e)
- [x] i think we're good to start optimizing the image now
- [x] on larger screen sizes, this text block should remain vertically-centered between the two images (https://cl.ly/6de120c4d88f)

**Comment by mfix22** [comment]
Hero background image size needs to be adjusted for mobile/tablet

**Comment by jakedex** [comment]
This is looking good! A bit more feedback:
- [x] Change hero image and ipad image from svg to png (should use same box-shadow as zack image)
- [x] hook up "read more" button
- [x] handle corner gradients on large displays (https://cl.ly/55f3b956ea52 and https://cl.ly/30c75b9ba484)
- [x] hero BG image changes sizes while loading... i'm fine doing something similar to what we ended up doing with the SZA hero BG if needed (https://cl.ly/cb179b85a63e)

**Comment by jakedex** [comment]
- [ ] hero bg image should maintain aspect ratio (https://cl.ly/9f9b7246c35c vs https://cl.ly/9c22d339a6cd)
