### ISSUE TITLE
hero terminal section fixes

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/next-site#5]
- [x] the feature bullets should be better centered, looks like an issue with the SVG checkmarks (https://cl.ly/25ea947194fa). namely, these should span the full width of the container
- [x] input/output animated lines should be the same (right line should have the same width/style as left)
- [x] terminal and file containers should all be vertically aligned (https://cl.ly/24fad4fdd72f)
- [x] border-radius on the file input/output containers is looking kinda weird on my larger monitor (https://cl.ly/ee8a86590117)
- [x] ideally, we'd have those lines above the file list container like: https://cl.ly/72072673c17d. 
- [x] said outlines in the file list container should be animated as well
- [x] terminal should be a bit shorter. ideally would have similar padding-bottom to that of terminal on zeit.co/now (and the figma doc) https://cl.ly/b1a0750903a1
- [x] terminal should have same box-shadow as left/right file-containers (could probably just copy css from figma)

**Comment by mfix22** [comment]
> input/output animated lines should be the same (right line should have the same width/style as left)

They are the _exact_ same `path` component. I copy pasted them between the SVG's

**Comment by jakedex** [comment]
Hmm, that's weird. Yeah, it's only on my larger monitor that they differ: https://cl.ly/c18051fc7460

**Comment by mfix22** [comment]
The image in that link is not really rendering for me.

**Comment by mfix22** [comment]
@jakedex i think this is good to close, but want to give it a final verification?

**Comment by jakedex** [comment]
Yeah! This looks great 👍
