### ISSUE TITLE
file list bug

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/next-site#9]
some of the "out" files are missing a period 

https://cl.ly/ea098f1427df

**Comment by mfix22** [comment]
Can you just post the images directly in GitHub? They are all showing up like this

<img width="1280" alt="screenshot 2019-01-30 14 50 54" src="https://user-images.githubusercontent.com/8397708/52018219-82d5e780-249e-11e9-874c-6aad450b9772.png">

**Comment by jakedex** [comment]
Will do going forward. That's really the whole image though.

**Comment by mfix22** [comment]
Ohhh sorry. hahah. Im on the fix (:
